name: CI
on:
    push:
        branches:
        - main
    pull_request:
    schedule:
        - cron:  '17 3 * * 0'

jobs:
    ruff:
        name: Ruff
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4
            with:
                submodules: true
        -   uses: actions/setup-python@v5
        -   name: "Main Script"
            run: |
                pip install ruff
                ruff check

    pytest:
        name: Pytest on Py${{ matrix.python-version }} ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                python-version: ['3.8', '3.10', '3.x']
                os: [ubuntu-latest, macos-latest]
        steps:
        -   uses: actions/checkout@v4
        -
            uses: actions/setup-python@v5
            with:
                python-version: ${{ matrix.python-version }}
        -   name: "Main Script"
            env:
                OS_NAME: ${{ matrix.os }}
            run: |
                EXTRA_INSTALL="numpy pybind11 meson-python ninja"
                PROJECT_INSTALL_FLAGS="--no-build-isolation"
                if [[ "$OS_NAME" == ubuntu-* ]]; then
                    ./.ci/install-silo-on-github.sh
                    PROJECT_INSTALL_FLAGS+=" --config-settings setup-args=-Duse-silo=true"
                fi

                curl -L -O https://tiker.net/ci-support-v0
                . ci-support-v0

                build_py_project_in_venv
                test_py_project

    mypy:
        name: Mypy
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4
        -
            uses: actions/setup-python@v5
            with:
                python-version: '3.x'
        -   name: "Main Script"
            run: |
                EXTRA_INSTALL="numpy pybind11 meson-python ninja mypy pytest"
                PROJECT_INSTALL_FLAGS="--no-build-isolation"

                curl -L -O https://tiker.net/ci-support-v0
                . ci-support-v0

                build_py_project_in_venv
                python -m mypy "$(basename $GITHUB_REPOSITORY)" test

    examples:
        name: Examples on Py${{ matrix.python-version }} ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                python-version: ['3.8', '3.x']
                os: [ubuntu-latest, macos-latest]
        steps:
        -   uses: actions/checkout@v4
        -
            uses: actions/setup-python@v5
            with:
                python-version: ${{ matrix.python-version }}
        -   name: "Main Script"
            env:
                OS_NAME: ${{ matrix.os }}
            run: |
                EXTRA_INSTALL="numpy pybind11 meson-python ninja"
                PROJECT_INSTALL_FLAGS="--no-build-isolation"
                if [[ "$OS_NAME" == ubuntu-* ]]; then
                    ./.ci/install-silo-on-github.sh
                    PROJECT_INSTALL_FLAGS+=" --config-settings setup-args=-Duse-silo=true"
                fi

                curl -L -O https://tiker.net/ci-support-v0
                . ci-support-v0

                build_py_project_in_venv
                run_examples --no-require-main

    docs:
        name: Documentation
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4
        -
            uses: actions/setup-python@v5
            with:
                python-version: '3.x'
        -   name: "Main Script"
            run: |
                EXTRA_INSTALL="numpy pybind11 meson-python ninja"
                PROJECT_INSTALL_FLAGS="--no-build-isolation --config-settings setup-args=-Duse-silo=true"
                ./.ci/install-silo-on-github.sh

                curl -L -O https://tiker.net/ci-support-v0
                . ci-support-v0

                build_py_project_in_venv
                build_docs

# vim: sw=4
