name: CI
on:
    push:
        branches:
        - main
    pull_request:
    schedule:
        - cron:  '17 3 * * 0'

jobs:
    flake8:
        name: Flake8
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -
            uses: actions/setup-python@v1
            with:
                # matches compat target in setup.py
                python-version: '3.6'
        -   name: "Main Script"
            run: |
                curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/main/prepare-and-run-flake8.sh
                . ./prepare-and-run-flake8.sh  "$(basename $GITHUB_REPOSITORY)" test examples

    pytest:
        name: Pytest on Py${{ matrix.python-version }} ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                # For some reason, the Silo build doesn't succeed on 3.6?
                python-version: [3.7, 3.x]
                os: [ubuntu-latest, macos-latest]
        steps:
        -   uses: actions/checkout@v2
        -
            uses: actions/setup-python@v1
            with:
                python-version: ${{ matrix.python-version }}
        -   name: "Main Script"
            run: |
                if [[ $(uname) == "Linux" ]]; then
                    ./.ci/install-silo-on-github.sh
                    USE_SILO="--use-silo"
                fi
                EXTRA_INSTALL="numpy pybind11"
                curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/main/ci-support.sh
                . ./ci-support.sh
                ./configure.py $USE_SILO
                build_py_project_in_venv
                test_py_project

    examples:
        name: Examples on Py${{ matrix.python-version }} ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                python-version: [3.6, 3.x]
                os: [ubuntu-latest, macos-latest]
        steps:
        -   uses: actions/checkout@v2
        -
            uses: actions/setup-python@v1
            with:
                python-version: ${{ matrix.python-version }}
        -   name: "Main Script"
            run: |
                # not expected to run without matplotlib and vtk
                rm examples/vtk-sample-elements.py

                if [[ $(uname) == "Linux" ]]; then
                    ./.ci/install-silo-on-github.sh
                    USE_SILO="--use-silo"
                fi
                EXTRA_INSTALL="numpy pybind11"
                curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/main/ci-support.sh
                . ./ci-support.sh
                ./configure.py $USE_SILO
                build_py_project_in_venv
                run_examples

    docs:
        name: Documentation
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -
            uses: actions/setup-python@v1
            with:
                python-version: '3.x'
        -   name: "Main Script"
            run: |
                ./.ci/install-silo-on-github.sh
                EXTRA_INSTALL="numpy pybind11"
                curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/main/ci-support.sh
                . ./ci-support.sh
                ./configure.py --use-silo
                build_py_project_in_venv
                build_docs

# vim: sw=4
